Repository jdomingu98/ft_transcendence_backend, pull requests merged in 2024-09, with the labels that each got.

#26 Enviar css a correos con templates html
  .pre-commit-config.yaml
  apps/user/v1/views.py
  requirements.txt
  templates/changePassword.html
  templates/changePassword/index.html
  templates/changePassword/styles.css
Labels: bug

#28 Betta v0.6.0
  .pre-commit-config.yaml
  README.md
  apps/user/migrations/0005_alter_user_email_alter_user_username.py
  apps/user/models.py
  apps/user/test_models.py
  apps/user/v1/serializers.py
  apps/user/v1/urls.py
  apps/user/v1/views.py
  pyproject.toml
  requirements.txt
  templates/changePassword.html
  templates/changePassword/index.html
  templates/changePassword/styles.css
Labels: enhancement

#25 feat: add more secure password validations
  apps/user/migrations/0005_alter_user_email_alter_user_username.py
  apps/user/models.py
  apps/user/v1/serializers.py
  apps/user/v1/tests/test_serializers.py
  apps/user/v1/tests/test_views.py
  backend/settings.py
Labels: enhancement

#29 Betta v0.7.0
  README.md
  apps/user/migrations/0005_alter_user_email_alter_user_username.py
  apps/user/models.py
  apps/user/v1/serializers.py
  apps/user/v1/tests/test_serializers.py
  apps/user/v1/tests/test_views.py
  backend/settings.py
Labels: enhancement

#30 OAuth implementation
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  apps/user/migrations/0006_user_id42.py
  apps/user/models.py
  apps/user/test_models.py
  apps/user/v1/serializers.py
  apps/user/v1/urls.py
  apps/user/v1/views.py
  backend/.env.example
  backend/utils/oauth_utils.py
  requirements.txt
Labels: enhancement

#35 feat(cache): add redis cache configuration
  backend/settings.py
  requirements.txt
Labels: enhancement

#33 feat(config): enable https connection and other security options
  .github/workflows/tests.yml
  backend/.env.example
  backend/settings.py
Labels: enhancement

#34 feat(build): Dockerize backend
  .dockerignore
  .github/workflows/tests.yml
  Dockerfile
  backend/.env.example
  backend/settings.py
  entrypoint.sh
  requirements.txt
Labels: enhancement

#38 create endpoint rud usuario
  .gitignore
  apps/game/migrations/0004_rename_total_goals_statistics_num_goals_against_and_more.py
  apps/game/models.py
  apps/user/migrations/0007_user_two_factor_enabled.py
  apps/user/models.py
  apps/user/v1/serializers.py
  apps/user/v1/tests/test_views.py
  apps/user/v1/urls.py
  apps/user/v1/views.py
  backend/utils/email_sender.py
  backend/utils/pass_reset_utils.py
  pyproject.toml
Labels: enhancement, refactor
