Repository jdomingu98/ft_transcendence_backend, pull requests merged in 2024-10, with the labels that each got.

#39 email validation error in oauth
  apps/user/v1/views.py
  backend/utils/oauth_utils.py
Labels: bug

#40 Endpoint OTP
  apps/user/migrations/0008_otpcode.py
  apps/user/models.py
  apps/user/v1/serializers.py
  apps/user/v1/views.py
  backend/settings.py
  backend/utils/otp_utils.py
  templates/oneTimePassword.html
Labels: enhancement

#43 Betta v0.10.0
  .gitignore
  README.md
  apps/game/migrations/0004_rename_total_goals_statistics_num_goals_against_and_more.py
  apps/game/models.py
  apps/user/migrations/0007_user_two_factor_enabled.py
  apps/user/migrations/0008_otpcode.py
  apps/user/models.py
  apps/user/v1/serializers.py
  apps/user/v1/tests/test_views.py
  apps/user/v1/urls.py
  apps/user/v1/views.py
  backend/settings.py
  backend/utils/email_sender.py
  backend/utils/oauth_utils.py
  backend/utils/otp_utils.py
  backend/utils/pass_reset_utils.py
  generateJwtKeys.sh
  pyproject.toml
  templates/oneTimePassword.html
Labels: enhancement

#45 feat: create confirm-register template
  templates/confirmRegistration.html
Labels: enhancement

#44 feat(language):add chinese language
  apps/user/enums.py
  apps/user/migrations/0009_alter_user_language.py
Labels: enhancement

#46 Endpoint account verified
  .github/workflows/tests.yml
  apps/user/migrations/0010_user_is_verified.py
  apps/user/models.py
  apps/user/v1/serializers.py
  apps/user/v1/views.py
  backend/.env.example
  backend/settings.py
  backend/utils/conf_reg_utils.py
  templates/confirmRegistration.html
Labels: enhancement

#41 feat(leaderboard): create leaderboard endpoint
  apps/user/manager.py
  apps/user/models.py
  apps/user/test_models.py
  apps/user/v1/serializers.py
  apps/user/v1/views.py
  backend/utils/authentication.py
Labels: enhancement

#42 feat: Add Statistics Fields to User Retrieve Serializer
  apps/game/migrations/0005_alter_statistics_time_played.py
  apps/game/models.py
  apps/user/manager.py
  apps/user/models.py
  apps/user/test_models.py
  apps/user/v1/serializers.py
  apps/user/v1/views.py
Labels: enhancement

#47 Betta v0.11.0
  .github/workflows/tests.yml
  README.md
  apps/game/migrations/0005_alter_statistics_time_played.py
  apps/game/models.py
  apps/user/enums.py
  apps/user/manager.py
  apps/user/migrations/0009_alter_user_language.py
  apps/user/migrations/0010_user_is_verified.py
  apps/user/models.py
  apps/user/test_models.py
  apps/user/v1/serializers.py
  apps/user/v1/views.py
  backend/.env.example
  backend/settings.py
  backend/utils/authentication.py
  backend/utils/conf_reg_utils.py
  backend/utils/otp_utils.py
  templates/confirmRegistration.html
Labels: enhancement

#51 feat: add translation literals
  apps/user/models.py
  apps/user/v1/serializers.py
  apps/user/v1/tests/test_serializers.py
  apps/user/v1/tests/test_views.py
  apps/user/v1/views.py
  backend/utils/authentication.py
  backend/utils/jwt_tokens.py
  backend/utils/mixins/custom_error_messages.py
Labels: enhancement

#48 Fix user ranking position calculation
  apps/user/v1/views.py
Labels: bug

#50 Refactor register
  apps/user/v1/tests/test_views.py
  apps/user/v1/views.py
Labels: refactor

#53 Betta v0.12.0
  README.md
  apps/user/models.py
  apps/user/v1/serializers.py
  apps/user/v1/tests/test_serializers.py
  apps/user/v1/tests/test_views.py
  apps/user/v1/views.py
  backend/utils/authentication.py
  backend/utils/jwt_tokens.py
  backend/utils/mixins/custom_error_messages.py
Labels: enhancement
